exports.data = [
    {
        "enhanceId":0,
        "costList":[
            0,0,0,0,0,0,0,0,
            1,1,1,1,1,1,1,1,
            2,2,2,2,2,2,2,2,
            3,3,3,3,3,3,3,3
        ],
        "property":[
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },
            {
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            },{
                "health":6,
                "attack":1,
                "critical":2,
                "strong":2,
                "accuracy":2,
                "reactivity":2,
                "speed":2
            }
        ]
    }
];
